# Generated by Django 5.1.4 on 2025-01-08 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_alter_review_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='movie_title',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
